baseURL = "https://www.webreaktor.nl"
languageCode = "nl"
title = "WebReaktor"
resourceDir = "resources"

[permalinks]
portfolio = "/:slug/"
footerteksten = "/:slug/"
website-laten-maken = "/:slug/"
webshop-laten-maken = "/:slug/"
branches = "/:slug/"



[security]
  [security.funcs]
    getenv = ["^HUGO_", "^WC_"]
